site_name: Результаты исследований
site_url: https://venezia03.github.io/Python/
use_directory_urls: true
site_description: Публикация результатов экспериментов
site_author: Dmitry Yaroslavov

theme:
  name: material
  language: ru
  features: 
    - navigation.tabs
    - navigation.sections
    - navigation.top 
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true

nav:
 - Главная: index.md
 - Исследование: 
    - Сравнение генераторов: research/generators.md
 - Практика: 
    - CI/CD: practice/ci.md